### PR TITLE
Fixed crash when flags where given after the image

### LINKED ISSUE #66: zypper-docker crashes if the options for the lp/lu commands are at the end
The following makes zypper-docker crash:

```
$ ./zypper-docker lu suma-docker-registry.suse.de/opensuse-old-alsa --bugzilla
```

Note that `--bugzilla` is at the end, and not between the command and the image.

### PR DESCRIPTION
**Pull request by mssola**
Fixes #66

Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

### CODE REVIEW

**Comment by mssola** [comment]
@flavio unit & integration tests are passing, and doing some manual testing everything looks alright. However, give it a good look because I'm not sure about this patch :)

**Comment by flavio** [comment]
Is there a way to write a regression test for that?

**Comment by mssola** [comment]
@flavio let me write an integration test that triggers the crash

**Comment by mssola** [comment]
@flavio done. As you can see, in this case `zypper-docker` will report that --bugzilla does not exist because it has to be set before the image.

**Comment by flavio** [comment]
Cool, please merge it once all the tests are green

**Pull request merged**
