### PR TITLE
Apply patches

### PR DESCRIPTION
**Pull request by flavio**
Initial implementation.

I need some help to extend the tests and cover this part of `patches.go`:

```go
// It appends the set flags with the given command.
func cmdWithFlags(cmd string, ctx *cli.Context) string {
        for _, name := range ctx.FlagNames() {
                // BEGIN UNCOVERED
                if value := ctx.String(name); value != "" {
                        var dash string
                        if len(name) == 1 {
                                dash = "-"
                        } else {
                                dash = "--"
                        }

                        cmd += fmt.Sprintf(" %v%s %s", dash, name, value)
                }
                // END UNCOVERED
        }
        return cmd
}
```

### CODE REVIEW

**Comment by flavio** [comment]
Ok, I consider the command ready. Please review it when you have some spare time.

**Comment by flavio** [comment]
I think we should add some flags to set the author and the maybe the message associated with the git commit; I'm not happy with the default values I set. What do you think?

**Comment by mssola** [comment]
Some comments on the code:
1. Rebase
2. The `test_helper.go` and the `mock_test.go` files serve the same purpose I think. We should merge them. You can also move some other helper functions from our test suite there.
3. Why did you remove the `-race` flag from the Makefile?

On the author & comment, I think that we should implement two things:
- As you proposed, add the `--author` and the `--comment` flags.
- If some of these two flags have not been set, prompt the user forcing him to enter some values.

Note that this should be implemented in another PR. We should open up a new issue about it,

**Comment by flavio** [comment]
> 3. Why did you remove the -race flag from the Makefile?

I got an error about `-race` not being supported, I thought it was related with my images being using a patched version of your climate tool (do you remember my old PR?). I was wrong. I'm going to revert it.

**Pull request merged**
