### PR TITLE
Resize the TTY after creating the container

### LINKED ISSUE #18: Resize the TTY
By default, container logs are sized like this: height=40 and width=80. This can be inconvenient for logs that are just too wide. For example, a simple `zypper lp` already breaks this size. In this case, docker will cut the output to 80 columns and append an arrow like this:

```
Repository | Name              | Category    | Severity | Status | Summary      
-----------+-------------------+-------------+----------+--------+--------------
OSS Update | openSUSE-2015-345 | recommended | moderate | needed | Recommended->
OSS Update | openSUSE-2015-497 | security    | moderate | needed | Security up->
```

We need to resize the TTY by performing a call the [resize endpoint](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#resize-a-container-tty). Sadly, the `dockerclient` does not implement a function targeting this endpoint.

Therefore, the solution would be to update our current [fork](https://github.com/mssola/dockerclient) of the `dockerclient` library and submit a PR to upstream. Meanwhile we would still keep on using our fork.

### PR DESCRIPTION
**Pull request by mssola**
Fixes #18

### CODE REVIEW

**Comment by mssola** [comment]
Note that the Docker CLI actually listens for the SIGWINCH signal in a separate goroutine and resizes the TTY also in this situation. IMHO this over-complicates the code, so I haven't implemented it.

@flavio what do you think ?

**Comment by flavio** [comment]
The code looks good. Right now I think we can just ignore SIGWINCH, however it would be nice to add it.

**Comment by mssola** [comment]
@flavio The problem with SIGWINCH is that to avoid having dangling goroutines, we would have to make sure to gracefully close said goroutine in the `startContainer` function. Since there are lots of places in which this function can return early, this would make the `startContainer` function even scarier.

**Comment by flavio** [comment]
I see. I don't think this is a top priority for us right now. Usually the containers spawned by zypper-docker have a really limited life.

**Pull request merged**
