### PR TITLE
migrate to vendor/

### LINKED ISSUE #100: migrate to vendor/ experiment
We're not testing nor using Go < 1.5 anymore, therefore we should use the vendor/ experiment which is also supported by Godeps.

### PR DESCRIPTION
**Pull request by monstermunchkin**
We're not testing nor using Go < 1.5 anymore, therefore we should use the
vendor/ experiment. Also, instead of using Godep, we are switching to
govend.

Resolves #100

Signed-off-by: Thomas Hipp <thipp@suse.com>

### CODE REVIEW

**Comment by mssola** [comment]
You should also update the `.travis.yml` file :wink:

**Comment by cyphar** [comment]
I think you should still commit the vendored code.

**Comment by flavio** [comment]
> I think you should still commit the vendored code.

+1

**Comment by monstermunchkin** [comment]
Updated `.travis.yml`. @cyphar, I never removed the vendored code, it's all there.

**Comment by mssola** [comment]
@monstermunchkin maybe you left some ? In Travis we get:

    flags.go:22:2: cannot find package "github.com/codegangsta/cli" in any of

**Comment by monstermunchkin** [comment]
I guess there's a `GO15VENDOREXPERIMENT=1` missing somewhere.

**Comment by monstermunchkin** [comment]
Ha! Now it works. Regarding the weird numbers git reports, maybe Godep previously just did some strange things ¯\\\_(ツ)\_/¯

**Pull request merged**
