### PR TITLE
Migrated from samalba/dockerclient to docker/engine-api

### LINKED ISSUE #87: Move to the new `docker/engine-api`
Docker recently released the [engine client API](https://github.com/docker/engine-api) in a separate project. This effectively replaces the need for the docker client being used. One important thing to note is that Docker is [using](https://github.com/docker/docker/blob/3a8d694e01d8c3353f49a3f220ee861769f8b4a5/api/client/cli.go#L46) this library in current master. This fixes notable issues with the docker client we're using: missing types/endpoints, outdated API, missing parameters, etc.

### PR DESCRIPTION
**Pull request by mssola**
Fixes #87

Signed-off-by: Miquel Sabaté <msabate@suse.com>

### CODE REVIEW

**Comment by flavio** [comment]
Everything looks good to me.

I've just one comment:
```go
// getDockerClient safely returns the singleton instance of the Docker client.
// In order to guarantee such safety, the instance has to be initialized when
// no goroutines are being executed concurrently (e.g. the `init` or the `main`
// function).
```
Why don't we use a mutex to enforce safety?

**Comment by mssola** [comment]
According to `go test -race` we don't have any problems here. But you're right, we should enforce it anyways. Better safe than sorry :)

**Comment by mssola** [comment]
Done. I've added a mutex that wraps the docker client. The `getDockerClient` now uses that mutex to guarantee safety inside of this function.

**Comment by mssola** [comment]
Fixed an issue raised by @cyphar

**Comment by flavio** [comment]
LGTM

**Comment by mssola** [comment]
There are some unexpected test failures. I'll fix that and then merge the code.

**Comment by mssola** [comment]
Don't merge this, I'm investigating on why Travis is freaking out on a piece of code...

**Pull request merged**
